### ISSUE TITLE
"Cannot read property '0' of undefined" with stm32f4_disco board

### ISSUE THREAD

**Issue by cgudrian** [trond-snekvik/vscode-devicetree#1]
It looks like the "array" property is undefined at this position:
https://github.com/trond-snekvik/vscode-devicetree/blob/0f4ca44a4b2df7d3506d953749443a0e0bb8ffb0/src/extension.ts#L468

**Comment by trond-snekvik** [comment]
Thanks! I have gone through the recent changes and added more undefined checks throughout in commit 5671ea5

**Comment by cgudrian** [comment]
Thanks for the quick fix!
