### ISSUE TITLE
How do you configure this extension?

### ISSUE THREAD

**Issue by trueb2** [trond-snekvik/vscode-devicetree#3]
![Screen Shot 2021-02-03 at 10 21 20 AM](https://user-images.githubusercontent.com/8592049/106776303-90805380-6609-11eb-9ca8-39bd1e5183e8.png)

I have updated the settings with paths that are correct. I also tried the expanded version of workspaceFolder
```
    "devicetree.zephyr": "${workspaceFolder}/zephyr",
    "devicetree.west": "/opt/homebrew/bin/west"
 
```

**Comment by trueb2** [comment]
![Screen Shot 2021-02-03 at 10 23 25 AM](https://user-images.githubusercontent.com/8592049/106776620-db01d000-6609-11eb-8ba9-2ae384e2a854.png)

There are no board choice options that can be selected.

**Comment by trueb2** [comment]
![Screen Shot 2021-02-03 at 10 27 18 AM](https://user-images.githubusercontent.com/8592049/106777213-667b6100-660a-11eb-993d-9cce3cdfb718.png)

One more screenshot of partially semantically parsed dts.

**Comment by trond-snekvik** [comment]
Hey, this seems odd, looks like you're doing everything right. The west failure is likely the root cause here. What is the output of `/opt/homebrew/bin/west -V` if you run it from command line? Do you get the same result if you restart vscode?

Also, just to make sure, is `devicetree.west` configured in the workspace settings, and if not, is there some empty or invalid value for that setting in your workspace or folder settings?

**Comment by trueb2** [comment]
Curious. Maybe this is a homebrew/python3 issue.
```
user@hostname asdf-folder % west -V 
zsh: /opt/homebrew/bin/west: bad interpreter: /opt/homebrew/opt/python@3.9/bin/python3.9: no such file or directory
West version: v0.8.0
user@hostname asdf-folder % /opt/homebrew/bin/west -V 
zsh: /opt/homebrew/bin/west: bad interpreter: /opt/homebrew/opt/python@3.9/bin/python3.9: no such file or directory
```

Sometimes, I get that error message, but it hasn't impacted anything else.

**Comment by trueb2** [comment]
It was a homebrew error! I am not sure how I ended up with an `/opt/homebrew/bin/west`, but I also have a `/usr/local/homebrew/bin/west`. That second one works. 

I do not have a python3 install under the arm homebrew installation (/opt/homebrew), but I must have at one point tried to install west with the arm python before completely removing it, leaving a bad west executable in my PATH.
