### ISSUE TITLE
Configuring extension

### ISSUE THREAD

**Issue by ryangenz** [trond-snekvik/vscode-devicetree#7]
Like the previous post from trueb2, I'm also getting the message that says:
"DeviceTree: Unable to find board."

This message pops every time I open a .overlay file.

Also when I open a .dts file I do not get the "Unable to find board" message but under the DEVICETREE accordion tab it only says: 
"Devicetree context view: 
When you open a DeviceTree file, it will show up here, along with information about its board and configuration" 

So something is not configured right, but there are no instructions under 'Installation' in README.md

**Comment by trond-snekvik** [comment]
Hi, this is likely the extension not being able to find or detect Zephyr. Try setting the Zephyr path in the devicetree part of the vscode settings. If this doesn't work, try setting the west path and set the default board to something zephyr ships with, like `nrf52dk_nrf52832`.

If you still have no luck, I'd need some more details about your environment, so I can reproduce it. Your OS, Zephyr version, West version and which folders from your Zephyr environment are in your vscode workspace would all be very helpful.

**Comment by ryangenz** [comment]
Could you give me an example of what Zephyr path should look like? Is it the same as the ZEPHYR_BASE environment variable or should it point to a specific script file?

**Comment by trond-snekvik** [comment]
Yep, the absolute path to the zephyr folder, just like ZEPHYR_BASE 👍 It'll attempt to use your ZEPHYR_BASE as well, but I get varying results with this across different platforms, there's just too many variations in setups

**Comment by ryangenz** [comment]
This did it. Thank you.
For some reason this setting had a path that was not correct at all, and I do not believe that I had set it upon installation so I really don't know where it came from.
Anyway, all good 👍
Thanks again!

**Comment by trond-snekvik** [comment]
Alright, I'll take a look at the defaults and the documentation to see if this can be improved in the future
